# Generated by Django 2.1.1 on 2018-09-23 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20180923_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='responded_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feeds.Post'),
        ),
    ]
