# Generated by Django 2.1.1 on 2018-09-24 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_reactions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reactions',
            options={'verbose_name_plural': 'Reactions'},
        ),
    ]
